add_rules("mode.debug", "mode.release")
add_requires("ffmpeg")
add_requires("libpng")
add_requires("fmt")
target("mp4topng")
    set_kind("binary")
    set_languages("c++17")
    add_files("*.cpp")
    add_packages("ffmpeg", "libpng")
    add_packages("fmt")